# Generated by Django 3.0.8 on 2020-07-05 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('search_sequence', models.TextField()),
                ('Created date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=32)),
                ('result', models.TextField()),
            ],
        ),
    ]
