# Generated by Django 3.0.8 on 2020-07-06 00:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sequencesearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsequence',
            name='Created date',
        ),
        migrations.AddField(
            model_name='searchsequence',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 7, 6, 0, 59, 42, 715525, tzinfo=utc), verbose_name='Created date'),
            preserve_default=False,
        ),
    ]
